services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: kneu
      POSTGRES_PASSWORD: kneu
      POSTGRES_DB: kneu
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
